# Author: Collin Moon
# Configured the hardware Cisco switches
# Ansible Docs: https://docs.ansible.com/ansible/latest/collections/cisco/ios/index.html
# Ansible Docs: https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_l2_interfaces_module.html#ansible-collections-cisco-ios-ios-l2-interfaces-module
# Ansible Docs: https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_vlans_module.html#ansible-collections-cisco-ios-ios-vlans-module

---
- name: Configures Cisco Hardware Switches
  hosts: Cisco_Switch_2
  gather_facts: false

  #  switch 2
  tasks:
    - name: Create VLANs 110-119 on Infrastructure 3-4
      cisco.ios.ios_vlans:
        config:
        - name: Inf_3_External
          vlan_id: 110
          state: active
          shutdown: disabled
        - name: Inf_3_Internal
          vlan_id: 111
          state: active
          shutdown: disabled
        - name: Inf_3_Users
          vlan_id: 112
          state: active
          shutdown: disabled
        - name: Inf_3_Guest
          vlan_id: 113
          state: active
          shutdown: disabled
        - name: Inf_3_DMZ
          vlan_id: 114
          state: active
          shutdown: disabled
        - name: Inf_4_External
          vlan_id: 115
          state: active
          shutdown: disabled 
        - name: Inf_4_Internal
          vlan_id: 116
          state: active
          shutdown: disabled 
        - name: Inf_4_Users
          vlan_id: 117
          state: active
          shutdown: disabled 
        - name: Inf_4_Guest
          vlan_id: 118
          state: active
          shutdown: disabled
        - name: Inf_4_DMZ
          vlan_id: 119
          state: active
          shutdown: disabled 
        state: replaced #Replaces device configuration of listed VLANs with provided configuration

#switch 2

    - name: Configure G1/0/2-4 as VLAN 110
      cisco.ios.ios_l2_interfaces:
        config:
        - name: GigabitEthernet1/0/2
          mode: access
          access: 
            vlan: 110
        - name: GigabitEthernet1/0/3
          mode: access
          access: 
            vlan: 110
        - name: GigabitEthernet1/0/4
          mode: access
          access: 
            vlan: 110
        - name: GigabitEthernet1/0/5
          mode: access
          access: 
            vlan: 110                             
        state: replaced #Replaces device configuration of listed l2 interfaces with provided configuration

    - name: Configure G1/0/6-9 as VLAN 111
      cisco.ios.ios_l2_interfaces:
        config:
        - name: GigabitEthernet1/0/6
          mode: access
          access: 
            vlan: 111
        - name: GigabitEthernet1/0/7
          mode: access
          access: 
            vlan: 111
        - name: GigabitEthernet1/0/8
          mode: access
          access: 
            vlan: 111
        - name: GigabitEthernet1/0/9
          mode: access
          access: 
            vlan: 111                             
        state: replaced #Replaces device configuration of listed l2 interfaces with provided configuration

    - name: Configure G1/0/10-13 as VLAN 112
      cisco.ios.ios_l2_interfaces:
        config:
        - name: GigabitEthernet1/0/10
          mode: access
          access: 
            vlan: 112
        - name: GigabitEthernet1/0/11
          mode: access
          access: 
            vlan: 112
        - name: GigabitEthernet1/0/12
          mode: access
          access: 
            vlan: 112
        - name: GigabitEthernet1/0/13
          mode: access
          access: 
            vlan: 112                              
        state: replaced #Replaces device configuration of listed l2 interfaces with provided configuration

    - name: Configure G1/0/14-17 as VLAN 113
      cisco.ios.ios_l2_interfaces:
        config:
        - name: GigabitEthernet1/0/14
          mode: access
          access: 
            vlan: 113
        - name: GigabitEthernet1/0/15
          mode: access
          access: 
            vlan: 113
        - name: GigabitEthernet1/0/16
          mode: access
          access: 
            vlan: 113
        - name: GigabitEthernet1/0/17
          mode: access
          access: 
            vlan: 113                              
        state: replaced #Replaces device configuration of listed l2 interfaces with provided configuration

    - name: Configure G1/0/18-21 as VLAN 114
      cisco.ios.ios_l2_interfaces:
        config:
        - name: GigabitEthernet1/0/18
          mode: access
          access: 
            vlan: 114
        - name: GigabitEthernet1/0/19
          mode: access
          access: 
            vlan: 114
        - name: GigabitEthernet1/0/20
          mode: access
          access: 
            vlan: 114
        - name: GigabitEthernet1/0/21
          mode: access
          access: 
            vlan: 114                              
        state: replaced #Replaces device configuration of listed l2 interfaces with provided configuration

    - name: Configure G1/0/22-25 as VLAN 115
      cisco.ios.ios_l2_interfaces:
        config:
        - name: GigabitEthernet1/0/22
          mode: access
          access: 
            vlan: 115
        - name: GigabitEthernet1/0/23
          mode: access
          access: 
            vlan: 115
        - name: GigabitEthernet1/0/24
          mode: access
          access: 
            vlan: 115
        - name: GigabitEthernet1/0/25
          mode: access
          access: 
            vlan: 115                             
        state: replaced #Replaces device configuration of listed l2 interfaces with provided configuration

    - name: Configure G1/0/26-29 as VLAN 116
      cisco.ios.ios_l2_interfaces:
        config:
        - name: GigabitEthernet1/0/26
          mode: access
          access: 
            vlan: 116
        - name: GigabitEthernet1/0/27
          mode: access
          access: 
            vlan: 116
        - name: GigabitEthernet1/0/28
          mode: access
          access: 
            vlan: 116
        - name: GigabitEthernet1/0/29
          mode: access
          access: 
            vlan: 116                            
        state: replaced #Replaces device configuration of listed l2 interfaces with provided configuration

    - name: Configure G1/0/30-33 as VLAN 117
      cisco.ios.ios_l2_interfaces:
        config:
        - name: GigabitEthernet1/0/30
          mode: access
          access: 
            vlan: 117
        - name: GigabitEthernet1/0/31
          mode: access
          access: 
            vlan: 117
        - name: GigabitEthernet1/0/32
          mode: access
          access: 
            vlan: 117
        - name: GigabitEthernet1/0/33
          mode: access
          access: 
            vlan: 117                             
        state: replaced #Replaces device configuration of listed l2 interfaces with provided configuration

    - name: Configure G1/0/34-37 as VLAN 118
      cisco.ios.ios_l2_interfaces:
        config:
        - name: GigabitEthernet1/0/34
          mode: access
          access: 
            vlan: 118
        - name: GigabitEthernet1/0/35
          mode: access
          access: 
            vlan: 118
        - name: GigabitEthernet1/0/36
          mode: access
          access: 
            vlan: 118
        - name: GigabitEthernet1/0/37
          mode: access
          access: 
            vlan: 118                             
        state: replaced #Replaces device configuration of listed l2 interfaces with provided configuration

    - name: Configure G1/0/38-41 as VLAN 119
      cisco.ios.ios_l2_interfaces:
        config:
        - name: GigabitEthernet1/0/38
          mode: access
          access: 
            vlan: 119
        - name: GigabitEthernet1/0/39
          mode: access
          access: 
            vlan: 119
        - name: GigabitEthernet1/0/40
          mode: access
          access: 
            vlan: 119
        - name: GigabitEthernet1/0/41
          mode: access
          access: 
            vlan: 119                              
        state: replaced #Replaces device configuration of listed l2 interfaces with provided configuration
    
    - name: Configure G1/0/1 as an 802.1q trunk
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0/1
            mode: trunk                         
        state: replaced #Replaces device configuration of listed l2 interfaces with provided configuration




