# Author: Collin Moon
# Configured the hardware Cisco switches
# Ansible Docs: https://docs.ansible.com/ansible/latest/collections/cisco/ios/index.html
# Ansible Docs: https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_l2_interfaces_module.html#ansible-collections-cisco-ios-ios-l2-interfaces-module
# Ansible Docs: https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_vlans_module.html#ansible-collections-cisco-ios-ios-vlans-module

---
- name: Configures Cisco Hardware Switches
  hosts: Cisco_Switch_1
  gather_facts: false

  # switch 1

  tasks:
    - name: Create VLANs 100-109 on Infrastructure 1-2
      cisco.ios.ios_vlans:
        config:
          - name: Inf_1_External
            vlan_id: 100
            state: active
            shutdown: disabled
          - name: Inf_1_Internal
            vlan_id: 101
            state: active
            shutdown: disabled
          - name: Inf_1_Users
            vlan_id: 102
            state: active
            shutdown: disabled
          - name: Inf_1_Guest
            vlan_id: 103
            state: active
            shutdown: disabled
          - name: Inf_1_DMZ
            vlan_id: 104
            state: active
            shutdown: disabled
          - name: Inf_2_External
            vlan_id: 105
            state: active
            shutdown: disabled
          - name: Inf_2_Internal
            vlan_id: 106
            state: active
            shutdown: disabled
          - name: Inf_2_Users
            vlan_id: 107
            state: active
            shutdown: disabled
          - name: Inf_2_Guest
            vlan_id: 108
            state: active
            shutdown: disabled
          - name: Inf_2_DMZ
            vlan_id: 109
            state: active
            shutdown: disabled
        state: merged

    # switch 1
    - name: Configure G1/0/2-5 as VLAN 100
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0/2
            mode: access
            access:
              vlan: 100
          - name: GigabitEthernet1/0/3
            mode: access
            access:
              vlan: 100
          - name: GigabitEthernet1/0/4
            mode: access
            access:
              vlan: 100
          - name: GigabitEthernet1/0/5
            mode: access
            access:
              vlan: 100
        # Replaces device configuration of listed l2 interfaces with provided configuration
        state: replaced

    - name: Configure G1/0/6-9 as VLAN 101
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0/6
            mode: access
            access:
              vlan: 101
          - name: GigabitEthernet1/0/7
            mode: access
            access:
              vlan: 101
          - name: GigabitEthernet1/0/8
            mode: access
            access:
              vlan: 101
          - name: GigabitEthernet1/0/9
            mode: access
            access:
              vlan: 101
        # Replaces device configuration of listed l2 interfaces with provided configuration
        state: replaced

    - name: Configure G1/0/10-13 as VLAN 102
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0/10
            mode: access
            access:
              vlan: 102
          - name: GigabitEthernet1/0/11
            mode: access
            access:
              vlan: 102
          - name: GigabitEthernet1/0/12
            mode: access
            access:
              vlan: 102
          - name: GigabitEthernet1/0/13
            mode: access
            access:
              vlan: 102
        # Replaces device configuration of listed l2 interfaces with provided configuration
        state: replaced

    - name: Configure G1/0/14-17 as VLAN 103
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0/14
            mode: access
            access:
              vlan: 103
          - name: GigabitEthernet1/0/15
            mode: access
            access:
              vlan: 103
          - name: GigabitEthernet1/0/16
            mode: access
            access:
              vlan: 103
          - name: GigabitEthernet1/0/17
            mode: access
            access:
              vlan: 103
        # Replaces device configuration of listed l2 interfaces with provided configuration
        state: replaced

    - name: Configure G1/0/18-21 as VLAN 104
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0/18
            mode: access
            access:
              vlan: 104
          - name: GigabitEthernet1/0/19
            mode: access
            access:
              vlan: 104
          - name: GigabitEthernet1/0/20
            mode: access
            access:
              vlan: 104
          - name: GigabitEthernet1/0/21
            mode: access
            access:
              vlan: 104
        # Replaces device configuration of listed l2 interfaces with provided configuration
        state: replaced

    - name: Configure G1/0/22-25 as VLAN 105
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0/22
            mode: access
            access:
              vlan: 105
          - name: GigabitEthernet1/0/23
            mode: access
            access:
              vlan: 105
          - name: GigabitEthernet1/0/24
            mode: access
            access:
              vlan: 105
          - name: GigabitEthernet1/0/25
            mode: access
            access:
              vlan: 105
        # Replaces device configuration of listed l2 interfaces with provided configuration
        state: replaced

    - name: Configure G1/0/26-29 as VLAN 106
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0/26
            mode: access
            access:
              vlan: 106
          - name: GigabitEthernet1/0/27
            mode: access
            access:
              vlan: 106
          - name: GigabitEthernet1/0/28
            mode: access
            access:
              vlan: 106
          - name: GigabitEthernet1/0/29
            mode: access
            access:
              vlan: 106
        # Replaces device configuration of listed l2 interfaces with provided configuration
        state: replaced

    - name: Configure G1/0/30-33 as VLAN 107
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0/30
            mode: access
            access:
              vlan: 107
          - name: GigabitEthernet1/0/31
            mode: access
            access:
              vlan: 107
          - name: GigabitEthernet1/0/32
            mode: access
            access:
              vlan: 107
          - name: GigabitEthernet1/0/33
            mode: access
            access:
              vlan: 107
        # Replaces device configuration of listed l2 interfaces with provided configuration
        state: replaced

    - name: Configure G1/0/34-37 as VLAN 108
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0/34
            mode: access
            access:
              vlan: 108
          - name: GigabitEthernet1/0/35
            mode: access
            access:
              vlan: 108
          - name: GigabitEthernet1/0/36
            mode: access
            access:
              vlan: 108
          - name: GigabitEthernet1/0/37
            mode: access
            access:
              vlan: 108
        # Replaces device configuration of listed l2 interfaces with provided configuration
        state: replaced

    - name: Configure G1/0/38-41 as VLAN 109
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0/38
            mode: access
            access:
              vlan: 109
          - name: GigabitEthernet1/0/39
            mode: access
            access:
              vlan: 109
          - name: GigabitEthernet1/0/40
            mode: access
            access:
              vlan: 109
          - name: GigabitEthernet1/0/41
            mode: access
            access:
              vlan: 109
        # Replaces device configuration of listed l2 interfaces with provided configuration
        state: replaced

    - name: Configure G1/0/1 as an 802.1q trunk
      cisco.ios.ios_l2_interfaces:
        config:
          - name: GigabitEthernet1/0/1
            mode: trunk
        # Replaces device configuration of listed l2 interfaces with provided configuration
        state: replaced
