---

#Reference https://docs.ansible.com/ansible/latest/network/user_guide/platform_ios.html

cisco_switches:
  hosts:
    Cisco_Switch_1:
      ansible_host: 172.16.0.10
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: cisco.ios.ios
      ansible_become: yes
      ansible_become_method: enable
      ansible_become_password: target
      ansible_user: admin
      ansible_password: target
    Cisco_Switch_2:
      ansible_host: 172.16.0.11
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: cisco.ios.ios
      ansible_become: yes
      ansible_become_method: enable
      ansible_become_password: target
      ansible_user: admin
      ansible_password: target
