---
cisco_switches:
  hosts:
    Cisco_Switch_1:
      ansible_host: 172.16.0.10
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: cisco.ios.ios
      ansible_user: admin
      ansible_password: target
    Cisco_Switch_2:
      ansible_host: 172.16.0.11
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: cisco.ios.ios
      ansible_user: admin
      ansible_password: target