---
- name: Merge provided configuration with device configuration
  vyos.vyos.vyos_interfaces:
    config:
    - name: eth0
      description: Configured by Ansible
      enabled: true
    state: merged