---
- name: Merge provided configuration with device configuration
  hosts: localhost
  gather_facts: yes
  vyos.vyos.vyos_interfaces:
    config:
    - name: eth0
      description: Configured by Ansible
      enabled: true
    state: merged