# Author: Collin Moon
# Configured the hardware Cisco switches
# Ansible Docs: https://docs.ansible.com/ansible/latest/collections/cisco/ios/index.html

---
- name: Configures Cisco Hardware Switches
  hosts: localhost
  gather_facts: false
  collections:
    - cisco.ios

  # switch 1

  tasks:
    - name: Create VLANs 100-109 on Infrastructure 1-2
      ios_vlans:
        config:
          - name: Vlan_100
            vlan_id: 100
            state: active
            shutdwon: disabled
        state: merged
