#Creates the two infrastructure vSwitches and ISP vSwitch on the Capstone ESXi server
#mtu defaults to 1500
#port defaults to 443
#username defaults to VMWARE_USER env var from AWX
#password defaults to VMWARE_PASSWORD env var from AWX
#valid certs defaults to yes for SSL forced connections

#vlan-id defaults to 0


---
- name: Create vSwitches and Port Groups
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  tasks:
    - name: Add Infrastructure 1-2 vSwitch
      vmware_vswitch:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        switch: infrastructure_1_2_vSwitch
        nics: vmnic1
      delegate_to: localhost

    - name: Add Infrastructure 3-4 vSwitch
      vmware_vswitch:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        switch: infrastructure_3_4_vSwitch
        nics: vmnic2
      delegate_to: localhost

    - name: Add ISP vSwitch
      vmware_vswitch:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        switch: isp_vSwitch
        nics: vmnic3
      delegate_to: localhost
  
    - name: Add Infrastructure 1 PG External - VLAN 100
      vmware_portgroup:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        switch: "{{ vswitch_name }}"
        portgroup: Inf_1_External_PG
        vlan_id: 100
      delegate_to: localhost

