#Author: Collin Moon
#Deletes an Ubuntu test VM from a template
#Ansible Docs: https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html#ansible-collections-community-vmware-vmware-guest-module

#Defaults
#port defaults to 443
#username defaults to VMWARE_USER env var from AWX
#password defaults to VMWARE_PASSWORD env var from AWX
#valid certs defaults to yes for SSL forced connections
#power_on_after_clone defaults to yes
#state defaults to present
#controller_type defaults to ide
#type defaults to client (CD-ROM type)
#diskmode defaults to persistant
#type defaults to dhcp in networking

---
- name: Delete Ubuntu VMs from Template
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  tasks: 

  #Infrastrucuture 1
    - name: Delete Ubuntu Test VM in Inf 1 External Zone - VLAN 100
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Test Inf 1 External'
        template: Ubuntu_Test_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

    - name: Delete Ubuntu Test VM in Inf 1 Internal Zone - VLAN 101
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Test Inf 1 Internal'
        template: Ubuntu_Test_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

    - name: Delete Ubuntu Test VM in Inf 1 Users Zone - VLAN 102
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Test Inf 1 Users'
        template: Ubuntu_Test_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

    - name: Delete Ubuntu Test VM in Inf 1 Guest Zone - VLAN 103
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Test Inf 1 Guest'
        template: Ubuntu_Test_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

    - name: Delete Ubuntu Webserver VM in Inf 1 DMZ Zone - VLAN 104
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Webserver Inf 1 DMZ'
        template: Ubuntu_Webserver_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy  

  #Infrastrucuture 2
    - name: Delete Ubuntu Test VM in Inf 2 External Zone - VLAN 105
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Test Inf 2 External'
        template: Ubuntu_Test_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

    - name: Delete Ubuntu Test VM in Inf 2 Internal Zone - VLAN 106
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Test Inf 2 Internal'
        template: Ubuntu_Test_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

    - name: Delete Ubuntu Test VM in Inf 2 Users Zone - VLAN 107
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Test Inf 2 Users'
        template: Ubuntu_Test_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

    - name: Delete Ubuntu Test VM in Inf 2 Guest Zone - VLAN 108
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Test Inf 2 Guest'
        template: Ubuntu_Test_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

    - name: Delete Ubuntu Webserver VM in Inf 2 DMZ Zone - VLAN 109
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Webserver Inf 2 DMZ'
        template: Ubuntu_Webserver_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

  #Infrastrucuture 3
    - name: Delete Ubuntu Test VM in Inf 3 External Zone - VLAN 110
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Test Inf 3 External'
        template: Ubuntu_Test_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

    - name: Delete Ubuntu Test VM in Inf 3 Internal Zone - VLAN 111
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Test Inf 3 Internal'
        template: Ubuntu_Test_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

    - name: Delete Ubuntu Test VM in Inf 3 Users Zone - VLAN 112
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Test Inf 3 Users'
        template: Ubuntu_Test_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

    - name: Delete Ubuntu Test VM in Inf 3 Guest Zone - VLAN 113
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Test Inf 3 Guest'
        template: Ubuntu_Test_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

    - name: Delete Ubuntu Webserver VM in Inf 3 DMZ Zone - VLAN 114
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Webserver Inf 3 DMZ'
        template: Ubuntu_Webserver_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

  #Infrastrucuture 4
    - name: Delete Ubuntu Test VM in Inf 4 External Zone - VLAN 115
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Test Inf 4 External'
        template: Ubuntu_Test_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

    - name: Delete Ubuntu Test VM in Inf 4 Internal Zone - VLAN 116
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Test Inf 4 Internal'
        template: Ubuntu_Test_Template
        state: absent   
        force: yes
      delegate_to: localhost
      register: deploy

    - name: Delete Ubuntu Test VM in Inf 4 Users Zone - VLAN 117
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Test Inf 4 Users'
        template: Ubuntu_Test_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

    - name: Delete Ubuntu Test VM in Inf 4 Guest Zone - VLAN 118
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Test Inf 4 Guest'
        template: Ubuntu_Test_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy

    - name: Delete Ubuntu Webserver VM in Inf 4 DMZ Zone - VLAN 119
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'Ubuntu Webserver Inf 4 DMZ'
        template: Ubuntu_Webserver_Template
        state: absent
        force: yes
      delegate_to: localhost
      register: deploy