#Author: Collin Moon
#Deletes a VyOS VM from a template
#Ansible Docs: https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html#ansible-collections-community-vmware-vmware-guest-module

#Defaults
#port defaults to 443
#username defaults to VMWARE_USER env var from AWX
#password defaults to VMWARE_PASSWORD env var from AWX
#valid certs defaults to yes for SSL forced connections
#power_on_after_clone defaults to yes
#state defaults to present
#controller_type defaults to ide
#type defaults to client (CD-ROM type)
#diskmode defaults to persistant

---
- name: Delete VyOS VM from Template
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  tasks: 

    #Power off and delete all VyOS edge routers
    - name: Delete a virtual machine from a template for infrastructure 1
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'VyOS Infrastructure 1'
        state: absent
        force: yes      
      delegate_to: localhost
      register: deploy

    - name: Delete a virtual machine from a template for infrastructure 2
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'VyOS Infrastructure 2'
        state: absent
        force: yes     
      delegate_to: localhost
      register: deploy

    - name: Delete a virtual machine from a template for infrastructure 3
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'VyOS Infrastructure 3'
        state: absent
        force: yes     
      delegate_to: localhost
      register: deploy

    - name: Delete a virtual machine from a template for infrastructure 4
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: 'VyOS Infrastructure 4'
        state: absent
        force: yes      
      delegate_to: localhost
      register: deploy

    #Begin rollback of VyOS DHCP server to the snapshot before DHCP leases were offered
    - name: Power OFF VyOS DHCP Server
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        name: VyOS_DHCP_Server
        state: poweredoff
      delegate_to: localhost
      
    #DHCP server is powered down and now reverting to original snapshot
    - name: Roll back DHCP server to no leases snapshot
      vmware_guest_snapshot:
        hostname: '10.123.100.10'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: VyOS_DHCP_Server
        state: revert
        snapshot_name: DHCP_No_Leases
      delegate_to: localhost

    #DHCP server is rolled back, power back on VM
    - name: Power ON VyOS DHCP Server
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        name: VyOS_DHCP_Server
        state: poweredon
      delegate_to: localhost