---
- name: Merge VyOS VM to this config
  hosts: localhost
  gather_facts: false
  collections:
    - vyos.vyos


  tasks:
    - name: merges all device configuration with provided configuration
      vyos_l3_interfaces:
        - name: eth0
          ipv4:
            - address: 10.50.50.1
    - name: Creates Static IP's
      vyos_static_route:
        prefix: 10.50.50.5 # configured ip, randomly made
        mask: 24 # mask 255.255.255.0
        next_hop: 10.50.50.9 # next hop ip address
        ansible_connection: network_cli # SSH over CLI connection
    - name: Creates Static IP's # Can work on loop once i get a file for it
      vyos_static_route:
        prefix: 10.50.50.5 # configured ip, randomly made


# notes: (will delete later)

# ask about: NAT, Logging, how to use ansible_connection: network_cli

#https://docs.ansible.com/ansible/2.9/modules/list_of_network_modules.html#vyos everything for VyOS

#----------------------------------
# needed to install: "ansible-galaxy collection install vyos.vyos." for task1
# Task 1 DHCP and config of interfaces

# potential for looping: IP address for vlans? 
# Interfaces:     -
# eth0: dhcp     -creating a dictionary for each interface
# eth1: 10.50.50.1   -
#
# to use: - address: '{{ interfaces.eth0 }}'
#
#https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html

#------------------------

# Task 2: NAT
# uses base so no install 
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/iptables_module.html
# https://github.com/sterin/ansible-role-nat-router/tree/master/templates

#- name: NAT configuration (WIP)
#  iptables:
#      action: append # append replaces old configuration with new, Change to INSERT to insert instead of replace
#      chain: FORWARD # specifies what iptables need to be modified can be connected to in_interface
#      in_interface: eth0 # specifies the IN interface, where packets are about to go    >>Packet   >>in  >  out 
#      out_interface: eth1 #W here packets are being sent     in > >>out    >Packet
#      source: "{{ lan_ip_range }}"
#      match: conntrack
#      ctstate: NEW
#      jump: ACCEPT
#    notify: persist iptables

#------------------------

# Task 3: NTP (almost no documentation)

#------------------------

# Task 4: Static IP
#https://docs.ansible.com/ansible/2.9/modules/vyos_static_route_module.html#vyos-static-route-module

#------------------------

# Task 5: BGP
# going to attempt to just brute force bgp through commands