---
- name: Create a Nat Instance
  gather_facts: false
  hosts: ansible-host
  # connection: local
  collections:
    - vyos.vyos

  tasks:
    - name: Merge provided configuration with device configuration
      vyos_interfaces:
        config:
          - name: eth1
            description: Configured by Ansible
            enabled: true
        state: overridden

# - name: Configure Source NAT for our Inside network
#   vyos_config:
#     lines:
#       - set nat source rule 10 outbound-interface 'eth1' # Basically the exit door    > NAT >O
#       - set nat source rule 10 source address '192.168.0.5/24'
#       - set nat source rule 10 translation address masquerade
#     save: yes
#   delegate_to: localhost
#   register: deploy
# - name: Show the Configuration
#   vyos_command:
# commands:
# - show configuration commands
# how to check? >show nat source translations
# https://github.com/rcalvaga/vyos-ansible/blob/master/vyos-cfme-emb-ansible-launch-instance-and-configure-nat-gateway.yml
# https://support.vyos.io/en/kb/articles/nat-basics-2
