---

- name: Create a Nat Instance
  hosts: localhost
  gather_facts: True
  connection: local
  collections:
   - vyos.vyos

  tasks: 
  - name: Configure descriptions
    vyos_config:
      #timeout: 30
      lines:
      #- set interfaces ethernet eth0 address dhcp 
      - set interfaces ethernet eth1 description 'OUTSIDE' 
      #- set interfaces ethernet eth0 address '192.168.0.1/24' #This address can be set to anything
      - set interfaces ethernet eth0 description 'INSIDE' 
      save: yes
    ignore_errors: yes
    delegate_to: localhost
    register: deploy

  - name: Configure Source NAT for our Inside network
    vyos_config:
      lines:
      - set nat source rule 10 outbound-interface 'eth1' # Basically the exit door    > NAT >O
      - set nat source rule 10 source address '192.168.0.5/24' # These are the ip's that are pre-NAT, they are going to change to the interface IP
      - set nat source rule 10 translation address masquerade #  The masquerade target is effectively an alias to say "use whatever IP address is on the outgoing interface"
      save: yes
    delegate_to: localhost
    register: deploy

  - name: Show the Configuration
    vyos_command:  
      commands:
      - show configuration commands


# how to check? >show nat source translations 

# https://github.com/rcalvaga/vyos-ansible/blob/master/vyos-cfme-emb-ansible-launch-instance-and-configure-nat-gateway.yml
# https://support.vyos.io/en/kb/articles/nat-basics-2
