---
- name: Get Nat
  hosts: localhost
  gather_facts: false
  collections:
    - cisco.ios

  tasks:
## tasks file for nat
- name: Apply NAT Overload
  ios_config:
    src: nat-do.j2
  tags:
    - nat