#Author: Collin Moon
#Powers off the VyOS VM for each infrastructure
#Ansible Docs: https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html#ansible-collections-community-vmware-vmware-guest-module

#Defaults
#port defaults to 443
#username defaults to VMWARE_USER env var from AWX
#password defaults to VMWARE_PASSWORD env var from AWX
#valid certs defaults to yes for SSL forced connections
#power_on_after_clone defaults to yes
#state defaults to present
#controller_type defaults to ide
#type defaults to client (CD-ROM type)
#diskmode defaults to persistant

---
- name: Powers OFF VyOS Edge Router VMs
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  tasks: 
    - name: Power OFF VyOS VM for Infrastructure 1
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        name: VyOS Infrastructure 1
        state: poweredoff
      delegate_to: localhost
      

    - name: Power OFF VyOS VM for Infrastructure 2
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        name: VyOS Infrastructure 2
        state: poweredoff
      delegate_to: localhost

    - name: Power OFF VyOS VM for Infrastructure 3
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        name: VyOS Infrastructure 3
        state: poweredoff
      delegate_to: localhost

    - name: Power OFF VyOS VM for Infrastructure 4
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        name: VyOS Infrastructure 4
        state: poweredoff
      delegate_to: localhost  