
---
- name: Create Ubntu VMs for firewall
  hosts: localhost
  gather_facts: no
  collections:
    - community.vmware

  tasks: 
    - name: Create a shorewall VM for Infrastructure 1
      vmware_guest:
        hostname: '10.123.100.10'
        esxi_hostname: '10.123.100.9'
        datacenter: Datacenter
        folder: /Datacenter/vm
        name: Ubuntu Firewall 1
        template: Ubuntu_firewall_template
        state: poweredon
        disk:
        - size_gb: 10
          controller_type: lsilogicsas
          type: thin
          datastore: Capstone_Local_DS_VMs
        hardware:
          memory_mb: 1024
          num_cpus: 1
          num_cpu_cores_per_socket: 1
          scsi: paravirtual
          hotadd_cpu: True
          hotremove_cpu: True
          hotadd_memory: False
          version: 12 # Hardware version of virtual machine
          boot_firmware: efi
        cdrom:
            - controller_number: 0
              unit_number: 0
              state: present
              type: iso
              iso_path: '[Capstone_Local_DS] ISOs/Ubunto.iso'
        networks:
        - name: ISP_PG
        - name: Inf_1_External_PG
        - name: Temporary Configuration PG
        - name: Inf_2_External_PG
        - name: INF_1_Internal_PG
        - name: INF_2 Internal_PG
        - name: INF_1_PG_DMZ
      delegate_to: localhost
      register: deploy