---
vyos_routers:
  hosts:
    vyos:
      ansible_host: 172.16.0.200
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: vyos.vyos.vyos
      ansible_user: vyos
      ansible_password: vyos
