---
vyos_routers:
  hosts:
    vyos1:
      ansible_host: 172.16.0.200
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: vyos.vyos.vyos
      ansible_user: vyos
      ansible_password: vyos
    vyos2:
      ansible_host: 172.16.0.201
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: vyos.vyos.vyos
      ansible_user: vyos
      ansible_password: vyos
    vyos3:
      ansible_host: 172.16.0.202
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: vyos.vyos.vyos
      ansible_user: vyos
      ansible_password: vyos
    vyos4:
      ansible_host: 172.16.0.203
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: vyos.vyos.vyos
      ansible_user: vyos
      ansible_password: vyos
