# Created by Jack James
# sets interfaces and NAT
---
- name: Create ethernet and IP scheme
  gather_facts: false
  hosts: all
  # connection: local

  tasks:
    - name: Parse the configuration.
      vyos.vyos.vyos_interfaces:
        running_config:
          "set interfaces ethernet eth0 address 'dhcp'
          set interfaces ethernet eth1 address '10.0.0.1/28'
          set interfaces ethernet eth1 description 'static internal IP to shorewall'
          set interfaces ethernet eth2 description 'Configured from temp'"
        state: parsed

# set interfaces ethernet eth1 vif 200 description 'VIF - 200'

# - name: Configure Source NAT for our Inside network
#   vyos_config:
#     lines:
#       - set nat source rule 10 outbound-interface 'eth1' # Basically the exit door    > NAT >O
#       - set nat source rule 10 source address '192.168.0.5/24'
#       - set nat source rule 10 translation address masquerade
#     save: yes
#   delegate_to: localhost
#   register: deploy
# - name: Show the Configuration
#   vyos_command:
# commands:
# - show configuration commands
# how to check? >show nat source translations
# https://github.com/rcalvaga/vyos-ansible/blob/master/vyos-cfme-emb-ansible-launch-instance-and-configure-nat-gateway.yml
# https://support.vyos.io/en/kb/articles/nat-basics-2

